/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [MASP]
      ,[TENSP]
      ,[MALOAI]
      ,[MAMAU]
      ,[MOTA]
      ,[GIA]
      ,[NGAYTHEM]
      ,[MAGG]
      ,[KICHTHUOC]
      ,[SOLUONG]
      ,[NGAYSUA]
  FROM [SHOESSHOP].[dbo].[PRODUCT]